server:
  port: 8088

spring:
  application:
    name: cffexmember

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cffexmember?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: postgres
    password: suntao2015

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-handlers-package: com.example.cffexmember.config
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.cffexmember.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.cffexmember: debug

file:
  upload-dir:
    E:/Cingeswell